services:
  krayin-php-apache:
    build:
      args:
        container_project_path: /var/www/html/
        uid: 1519
        user: "www-data"   # استبدلنا $USER بقيمة مباشرة
      context: .
      dockerfile: ./Dockerfile
    image: krayin-php-apache
    volumes:
      - ./workspace/:/var/www/html/

  krayin-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.configs/mysql-data:/var/lib/mysql/

  krayin-redis:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.configs/redis-data:/data

  krayin-phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: krayin-mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M

  krayin-mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
